import turtle
def aqua() :
    turtle.penup()
    turtle.goto(-425,55)
    turtle.pendown()
    turtle.color("darkviolet")
    turtle.pensize(23)
    turtle.goto(-375,100)
    turtle.goto(-325,55)
    turtle.goto(-275,100)
    turtle.goto(-225,55)
    turtle.goto(-175,100)
    turtle.goto(-125,55)
    turtle.penup()
    turtle.goto(-425,-10)
    turtle.pendown()
    turtle.pensize(23)
    turtle.goto(-375,35)
    turtle.goto(-325,-10)
    turtle.goto(-275,35)
    turtle.goto(-225,-10)
    turtle.goto(-175,35)
    turtle.goto(-125,-10)
def pisces() :
    turtle.penup()
    turtle.goto(-380,-100)
    turtle.pendown()
    turtle.color("deeppink")
    turtle.pensize(23)
    turtle.seth(50)
    turtle.circle(210,80)
    turtle.penup()
    turtle.goto(-175,170)
    turtle.pendown()
    turtle.seth(230)
    turtle.circle(210,80)
    turtle.penup()
    turtle.goto(-400,35)
    turtle.pendown()
    turtle.goto(-150,35)
def aries() :
    turtle.penup()
    turtle.goto(-339,150)
    turtle.pendown()
    turtle.color("crimson")
    turtle.pensize(23)
    turtle.seth(130)
    turtle.circle(45,180)
    turtle.penup()
    turtle.goto(-275,-50)
    turtle.pendown()
    turtle.seth(87)
    turtle.circle(300,40)
    turtle.penup()
    turtle.goto(-275,-50)
    turtle.pendown()
    turtle.goto(-275,-110)
    turtle.penup()
    turtle.goto(-140,100)
    turtle.pendown()
    turtle.seth(60)
    turtle.circle(45,180)
    turtle.penup()
    turtle.goto(-215,150)
    turtle.pendown()
    turtle.seth(233)
    turtle.circle(300,40)
    turtle.penup()
def taurus() :
    turtle.penup()
    turtle.goto(-265,-110)
    turtle.pendown()
    turtle.color("darkorange")
    turtle.pensize(23)
    turtle.seth(9)
    turtle.circle(90,360)
    turtle.penup()
    turtle.goto(-265,70)
    turtle.pendown()
    turtle.seth(0)
    turtle.circle(150,65)
    turtle.penup()
    turtle.goto(-424,156)
    turtle.pendown()
    turtle.seth(295)
    turtle.circle(150,65)
    turtle.penup()
def gemini() :
    turtle.penup()
    turtle.goto(-155,-100)
    turtle.pendown()
    turtle.color("gold")
    turtle.pensize(23)
    turtle.seth(145)
    turtle.circle(210,70)
    turtle.penup()
    turtle.goto(-400,170)
    turtle.pendown()
    turtle.seth(325)
    turtle.circle(210,70)
    turtle.penup()
    turtle.goto(-330,135)
    turtle.pendown()
    turtle.goto(-330,-65)
    turtle.penup()
    turtle.goto(-225,135)
    turtle.pendown()
    turtle.goto(-225,-65)
def cancer() :
    turtle.penup()
    turtle.goto(-140,-20)
    turtle.pendown()
    turtle.color("red")
    turtle.pensize(23)
    turtle.seth(50)
    turtle.circle(50, 360)
    turtle.penup()
    turtle.goto(-400,-20)
    turtle.pendown()
    turtle.seth(310)
    turtle.circle(170, 100)
    turtle.penup()
    turtle.goto(-400,20)
    turtle.pendown()
    turtle.seth(-50)
    turtle.circle(50, 360)
    turtle.penup()
    turtle.goto(-140,85)
    turtle.pendown()
    turtle.seth(130)
    turtle.circle(170, 100)
def leo() :
    turtle.penup()
    turtle.goto(-340,-10)
    turtle.pendown()
    turtle.color("olivedrab")
    turtle.pensize(23)
    turtle.seth(110)
    turtle.circle(45,360)
    turtle.goto(-360,70)
    turtle.penup()
    turtle.goto(-192,137)
    turtle.pendown()
    turtle.seth(105)
    turtle.circle(90,190)
    turtle.penup()
    turtle.goto(-192,137)
    turtle.pendown()
    turtle.goto(-210,-50)
    turtle.seth(270)
    turtle.circle(30,190)
def virgo() :
    turtle.penup()
    turtle.goto(-380,170)
    turtle.pendown()
    turtle.color("forestgreen")
    turtle.pensize(23)
    turtle.goto(-380,-75)
    turtle.penup()
    turtle.goto(-300,120)
    turtle.pendown()
    turtle.seth(90)
    turtle.circle(40,180)
    turtle.penup()
    turtle.goto(-300,120)
    turtle.pendown()
    turtle.goto(-300,-75)
    turtle.penup()
    turtle.goto(-220,120)
    turtle.pendown()
    turtle.seth(90)
    turtle.circle(40,180)
    turtle.penup()
    turtle.goto(-220,120)
    turtle.pendown()
    turtle.goto(-220,10)
    turtle.seth(270)
    turtle.circle(200,40)
    turtle.penup()
    turtle.goto(-160,50)
    turtle.pendown()
    turtle.seth(90)
    turtle.circle(30,180)
    turtle.penup()
    turtle.goto(-255,-100)
    turtle.pendown()
    turtle.seth(40)
    turtle.circle(300,34)
def libra() :
    turtle.penup()
    turtle.goto(-125,55)
    turtle.pendown()
    turtle.pensize(23)
    turtle.color("mediumturquoise")
    turtle.goto(-200,55)
    turtle.seth(80)
    turtle.circle(75,200)
    turtle.penup()
    turtle.goto(-350,55)
    turtle.pendown()
    turtle.goto(-425,55)
    turtle.penup()
    turtle.goto(-125,-10)
    turtle.pendown()
    turtle.goto(-425,-10)
def scorpio() :
    turtle.penup()
    turtle.goto(-380,170)
    turtle.pendown()
    turtle.color("dodgerblue")
    turtle.pensize(23)
    turtle.goto(-380,-75)
    turtle.penup()
    turtle.goto(-300,120)
    turtle.pendown()
    turtle.seth(90)
    turtle.circle(40,180)
    turtle.penup()
    turtle.goto(-300,120)
    turtle.pendown()
    turtle.goto(-300,-75)
    turtle.penup()
    turtle.goto(-220,120)
    turtle.pendown()
    turtle.seth(90)
    turtle.circle(40,180)
    turtle.penup()
    turtle.goto(-220,120)
    turtle.pendown()
    turtle.goto(-220,-70)
    turtle.seth(300)
    turtle.circle(50,145)
    turtle.seth(155)
    turtle.circle(15,360,3)
def sagitta() :
    turtle.penup()
    turtle.goto(-380,-75)
    turtle.pendown()
    turtle.color("blue")
    turtle.pensize(23)
    turtle.goto(-175,170)
    turtle.seth(140)
    turtle.circle(30,360,3)
    turtle.penup()
    turtle.goto(-280,-65)
    turtle.pendown()
    turtle.goto(-380,25)
def capri() :
    turtle.penup()
    turtle.goto(-350,170)
    turtle.pendown()
    turtle.color("indigo")
    turtle.pensize(23)
    turtle.goto(-350,10)
    turtle.penup()
    turtle.goto(-270,120)
    turtle.pendown()
    turtle.seth(90)
    turtle.circle(40,180)
    turtle.penup()
    turtle.goto(-270,120)
    turtle.pendown()
    turtle.goto(-270,10)
    turtle.seth(270)
    turtle.circle(60,140)
    turtle.seth(40)
    turtle.circle(40,150)
    turtle.seth(240)
    turtle.circle(200,25)
    turtle.penup()
    turtle.goto(-295,-100)
    turtle.pendown()
    turtle.seth(0)
    turtle.circle(70,80)

print("⋆✦별자리 안내✦⋆")
print("⋆물병자리⋆ 01/20~02/18   ⋆물고기자리⋆ 02/19~03/20 ")
print("⋆양자리⋆ 03/21~04/19     ⋆황소자리⋆ 04/20~05/20 ")
print("⋆쌍둥이자리⋆ 05/21~06/21 ⋆게자리⋆ 06/22~07/22 ")
print("⋆사자자리⋆ 07/23~08/22   ⋆처녀자리⋆ 08/23~09/23 ")
print("⋆천칭자리⋆ 09/24~10/22   ⋆전갈자리⋆ 10/23~11/22 ")
print("⋆사수자리⋆ 11/23~12/24   ⋆염소자리⋆ 12/25~01/19 ")
print()
star = input("★11월의 운세를 알아보는 별자리 운세입니다. 별자리를 입력해주세요★ : ")
print()
print()
print("☆",star,"이시군요☆")
print()
print()
if star =='물병자리' :
        aqua()
        print("⋆✦",star,"운세입니다✦⋆:"," 그동안 가족이나 연인과의 만남이 드물었다면 오랜만에 가족이나 연인끼리 분위기 있는 카페나 레스토랑에서 식사하는 것도 좋습니다. 아무리 가까운 사이라도 몸이 멀어지면 마음도 멀어지는 법이니 가정과 개인의 사적인 일을 중시할 필요가 있습니다. 또한 투자보다는 저축이 유리합니다. 현금을 확보하고 유동성에 대비하는 게 조만간 당신에게 다가올 문제해결의 방안이 될 수도 있습니다.")

elif star =='물고기자리' :
        pisces()
        print("⋆✦",star,"운세입니다✦⋆:","지금 만나는 이성이 있다면 지금 당장의 만남이 이성관계로 이어지지 않는다고 해도 친구로서 좋은 인연을 유지하세요. 그러면 시간의 흐름이 당신이 원하는 대로 진행시켜 줄 겁니다. 또한 친구들 사이에서의 당신의 위치는 중재자 역할을 할 때 입니다. 의견이 잘 합치되지 않을 때에 대부분 당신이 의견들을 중재하고 결정을 내리게 될 것입니다. 물론 힘들 수도 있지만 중재자 역할만 잘 하면 이로 인해 생각지도 않았던 좋은 결과를 얻을 수도 있겠네요.")

elif star =='양자리' :
        aries()
        print("⋆✦",star,"운세입니다✦⋆:","이성친구를 사귀고 있으면서도 자신의 속 마음을 제대로 내비치지 못하는 당신에게 사랑을 고백할 수 있는 용기가 자신도 모르게 생길 겁니다. 당신의 사랑을 고백하는 게 좋습니다. 그렇지 않으면 당신의 사랑의 큐피트는 사라질 수도 있습니다. 평소의 수입과는 전혀 상관없는 불로소득을 얻는 시기 입니다. 뜻밖의 행운에 기뻐하는 것도 좋지만,쉽게 얻은 돈일수록 쉽게 나가니 금새 그 돈들이 사라진다고 해도 너무 마음에 두지 않는 게 좋습니다.")

elif star =='황소자리' :
        taurus()
        print("⋆✦",star,"운세입니다✦⋆:","한 번 뜻을 정했으면,그 길로 쭉 밀고 나가야 합니다. 어렵게 잡은 기회가 있다면,놓치지 않기 위해서라도 큰 변화의 흐름을 놓치지 않길 바랍니다. 재물과 금전,횡재수가 모두 매우 왕성한 달입니다. 잦은 기회가 아니니 지금 물러서면 후회로 다가 올 수 있으니 유념하시길 바랍니다. 연인에게 프로포즈를 준비하고 있다면 과감하게 당신의 사랑을 보여주세요. 지금 이 기회를 놓치면 결국 후회하게 됩니다. 지금 당신이 하고 있는 사랑이 짝사랑이건 아니건 상관없이 당신이 그렇게 목말라하고 그리워하는 당신의 사랑입니다.")

elif star =='쌍둥이자리' :
        gemini()
        print("⋆✦",star,"운세입니다✦⋆:","일에 대한 진행이 자신이 원하는 방향으로 진행되지 않는다고 자신의 나이를 탓하거나 주위 환경을 탓하는 건 결국 자신이 능력이 없음을 얘기하는 것과 같습니다. 이성과는 가능하면 멀리 거리를 두는 게 두 사람의 사랑을 위해서는 유리합니다. 이동해야 하는 상황이 있다면 매우 좋겠습니다. 이동하는 곳 마다 환대를 받을 것 입니다. 주위 사람들로부터 관심과 부러움을 한 몸에 받을 수 있겠습니다. 이동이 끝나는 시점에 다소 혼란스러울 수 있으나 큰 기운에는 영향을 끼치지 않으니 괜찮겠습니다. 안락함으로 이어지는 상황이 연출됩니다.")

elif star =='게자리' :
        cancer()
        print("⋆✦",star,"운세입니다✦⋆:","공부라던가,자신의 할 일에 매진하는 것도 좋지만 최근 친구들을 너무 내버려 둔 것은 아닌지요. 곤란한 일이 있다면 서로 돕겠다고 생각한 친구들에게 뭔가 좋지 않은 일이 벌어졌을 수도 있습니다. 먼저 친구나 지인에게 안부 전화라도 한 번 걸어보세요. 어렵고 힘들 때 상대방을 도우면 반드시 당신도 힘들 때 도움을 받을 수 있습니다. 공기와 같은 친구가 진정한 친구이며 그러기에 소중함을 잊고 지내는 경우가 많습니다. 챙겨야 할 시기입니다.")

elif star =='사자자리' :
        leo()
        print("⋆✦",star,"운세입니다✦⋆:","마음속에 가지고 있던 찜찜하고 내내 먹구름 낀 것처럼 불안했던 마음이 현실로 다가옵니다. 아무리 일은 일사천리로 진행되어 간다고 해도,어딘가 알 수 없는 곳에서부터 퍼져나가는 불안감은 아무래도 몸 상태가 좋지 않아질 거라는 신호였는지도 모릅니다. 건강은 지킬 수 있을 때 지켜는 게 최상의 비법입니다. 커플이라면 이 시기에는 서로의 건강에 관심을 가져주는 것도 사랑의 기운이 손상되는 것을 미연에 방지해 줄 것입니다.")

elif star =='처녀자리' :
        virgo()
        print("⋆✦",star,"운세입니다✦⋆:","시간이 무한대로 있는 것은 아닙니다. 오늘 할 일을 내일로,미루고 또 내일의 할 일을 모레로 미루고 그런 식으로 자꾸 일을 미루다 보면 어느 날,손 댈 수 없을 정도로 엉켜버린 일을 발견하고 후회하게 됩니다. 주변에서 아무리 놀자고 유혹해도 단호하게 뿌리치고 오늘 해야 할 일을 처리하는 단호한 자세를 가지는 게 유리합니다.")

elif star =='천칭자리' :
        libra()
        print("⋆✦",star,"운세입니다✦⋆:","그동안 지나치게 스트레스를 받은 탓인지 마음이 우울합니다. 스트레스는 만병의 근원,그대로 두면 건강상태는 점점 나빠지고 우울증이 진행되어서,손가락 하나 꼼짝하기 싫은 상태가 되어버립니다. 그러나 모처럼 운이 당신 쪽으로 돌아와 줬는데 그렇게 드러누워 있을 시간이 없습니다. 빨리 기운을 차리고 행동을 취하는 게 당신에게 유리합니다.")

elif star =='전갈자리' :
        scorpio()
        print("⋆✦",star,"운세입니다✦⋆:","이 달은 노력해온 일에 대한 현실적인 성과로 이어지는 아주 좋은 시기입니다. 고정적인 소득의 폭이 커지는 것은 물론 생각 했던 것 이상으로 많은 금전적 변화가 예측 되어집니다. 짧은 시간 내에 재물로 연결될 수 있는 일이 발생하게 되는 군요. 이러한 것을 인해 부정기적인 수입에도 대단히 좋은 영향을 줍니다. 가장 활발한 사회활동을 할 수 있으며 그로 인해서 많은 이득들을 얻게 되니 활동하시고,그리고 그것들을 얻으십시오.")

elif star =='사수자리' :
        sagitta()
        print("⋆✦",star,"운세입니다✦⋆:","회사 내에서 혹은 조직 내에서 에너지를 집중하게 됩니다. 그러다 자칫 마음에 드는 것들을 놓칠 것만 같아서 무리수를 띄우게 되고 그로 인해 인정은 받겠지만 도리어 대인관계에 마이너스적인 면으로 비춰질 수 있습니다. 중용과 조정이 필요할 것으로 보입니다. 이성문제를 심각하게 고민하게 됩니다. 그리고 그것은 남모를 아픔을 떠올리게 할지도 모르겠습니다. 하지만 친한 친구가 정신적인 조언자 역할을 하게 되면서 당신의 이성문제에 대한 해결책을 찾게 됩니다. 의외로 그 친구와 평소에 하기 어려웠던 얘기도 순조롭게 잘 풀리는 행운이 따르게 됩니다.")

elif star =='염소자리' :
        capri()
        print("⋆✦",star,"운세입니다✦⋆:","왠지 모를 맥 빠지는 듯한 기운을 느끼게 됩니다. 사회활동에서의 위기감이랄까? 심하면 그런 것들에 빠질 수도 있겠군요. 사실 당신이 너무 앞만 보고 달려온 느낌이 든답니다. 마음을 속이지 않고 행동했었어야만 했는데요. 약간의 비밀스러움이 주변인들로 하여금 당신에게 거부감을 느끼게 할런지도 모르겠네요. 재정적인 문제는 순조롭게 잘 풀려나가게 됩니다. 당신이 걱정하지 않았던 상황도 주변에서 해결책을 제시해주어서 당신은 아주 행복한 상황에 놓이게 됩니다. 문제는 당신의 마음자세인데요. 속도만 잘 조절하면 되겠습니다.")

else :
    print("✦다시 입력해주세요. 띄어쓰기X, ~자리 꼭 붙혀주세요✦")
